### ISSUE TITLE
Issue migrating to Spring-boot 2.1.x / ElasticSearch 6.4.3

### ISSUE THREAD

**Issue by DanielFran** [VanRoy/spring-data-jest#102]
Current situation:

Spring-boot [**2.1.0**](https://github.com/spring-projects/spring-boot/releases/tag/v2.1.0.RC1) (since 2.1.0.RC1) is targetting elasticseach **6.4.2**
Spring-boot [**2.1.1**](https://github.com/spring-projects/spring-boot/releases/tag/v2.1.1.RELEASE) is targeting elasticseach **6.4.3**

Both use Jest **6.3.1**.

Issue found from logs:

_03:12:14.056 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - 
***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call the method org.elasticsearch.common.xcontent.XContentBuilder.string()Ljava/lang/String; but it does not exist. Its class, org.elasticsearch.common.xcontent.XContentBuilder, is available from the following locations:
    jar:file:/home/travis/app/app.war!/WEB-INF/lib/elasticsearch-x-content-6.4.3.jar!/org/elasticsearch/common/xcontent/XContentBuilder.class
It was loaded from the following location:
    jar:file:/home/travis/app/app.war!/WEB-INF/lib/elasticsearch-x-content-6.4.3.jar!/
Action:
Correct the classpath of your application so that it contains a single, compatible version of org.elasticsearch.common.xcontent.XContentBuilder_

**Comment by DanielFran** [comment]
After validating spring-data-elasticsearch version, after 3.1.3.RELEASE (spring-data-releasetrain version Lovelace-SR3) it switched to use [elasticsearch.version = 6.3.0](https://github.com/spring-projects/spring-data-elasticsearch/compare/3.1.3.RELEASE...master), so it will need an update in the next version.

**Comment by VanRoy** [comment]
@DanielFran , Thanks a lot for your feedback. I try to keep closest as possible to SpringDataElasticsearch. Currently SDES is based on ES 6.2.x . 
I will upgrade to 6.4.x as soon as SDES will be aligned to 6.4.x.
For now, I think that your solution ( downgrade to ES 6.3.x ) is the best workaround.

**Comment by aheritier** [comment]
@VanRoy  The solution is stay / downgrade to 6.2
The problem is starting with 6.3.0 which removed the `string()` method
The fix done in SDS  is https://github.com/spring-projects/spring-data-elasticsearch/commit/2f0b9b718b52bffe499e846d89fe2209aea2a536#diff-930eab647a65ec0182e998f9e0c010d8R57

**Comment by DanielFran** [comment]
This is SDES alignment with ES versions:
| spring data elasticsearch | elasticsearch |

|:-------------------------:|:-------------:|

| 3.2.x | 6.5.0 |

| 3.1.x | 6.2.2 |

| 3.0.x | 5.5.0 |

| 2.1.x | 2.4.0 |

| 2.0.x | 2.2.0 |

| 1.3.x | 1.5.2 |

**Comment by dasun** [comment]
@DanielFran 

So now, if we are using Spring Boot 2.1.2 with spring-data-elasticsearch 3.1.4, should we force downgrade elasticsearch.version to  6.2.2? Because spring boot defines elasticsearch version as 6.4.3 in https://github.com/spring-projects/spring-boot/blob/v2.1.2.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml.

**Comment by DanielFran** [comment]
@dasun, yes you need to downgrade to 6.2.x.
See @aheritier comments...

**Comment by VanRoy** [comment]
@DanielFran @dasun @aheritier I published an intermediary version 3.2.1 that is compatible with ES 6.4.3 with help of @dasun.
It will be usable until SpringDataES Moore release will be published.

**Comment by DanielFran** [comment]
Thanks @deyaeddin for the fix and @VanRoy for the new release
