### ISSUE TITLE
Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by thomazgaio** [VanRoy/spring-data-jest#107]
My problem was that I had an local Elasticsearch and everything was fine, but once we started an AWS ES I wasn't able to connect to Transport Client.

So, I added spring-data-jest dependency to my Spring Data Elasticsearch project that I already have and followed the steps on README file.

But when trying to run the application I am getting:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'articleRepository': Invocation of init method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository]: Constructor threw exception; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain`

I don't know much about AWS ES or AWS services at all.
Can you help me to see what I am missing?

**Comment by VanRoy** [comment]
Hi @thomazgaio , to successfully connect to AWS ES, you need to provide valid credentials to your application.
There are many ways for that, like provide aws_access_key_id and aws_secret_access_key system environment variable to your application.
For more details about that, you can look here : https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html
