### ISSUE TITLE
Problem with AutoConfiguration Order 

### ISSUE THREAD

**Issue by arman7797** [VanRoy/spring-data-jest#109]
There is a problem related to ElasticsearchJestAWSAutoConfiguration with spring cloud.
Spring Cloud has many autoconfiguration classes:

- ContextRegionProviderAutoConfiguration: Creates RegionProvider beanDefinition.
- ContextCredentialsAutoConfiguration: Creates AWSCredentionProvider beanDefinition.
- and many more.

Current implementation waits for ContextRegionProviderAutoConfiguration to define beanDefinition then starts configuring JestAWS.
```
@AutoConfigureAfter(name = "org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration")
```

But problem is in 
```
@Bean
@ConditionalOnMissingBean(AWSCredentialsProvider.class)
public AWSCredentialsProvider awsCredentialsProvider() {
	return new DefaultAWSCredentialsProviderChain();
}
```
ElasticsearchJestAWSAutoConfiguration should also wait for ContextCredentialsAutoConfiguration to define AWSCredentialsProvider.

So my solution is to add ContextCredentialsAutoConfiguration to AutoConfigureAfter
```
@AutoConfigureAfter(name = {
        "org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration",
        "org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration"
})
```

**Comment by VanRoy** [comment]
Thanks a lot.
It's available now on release 3.2.2.
