### ISSUE TITLE
Question - Configuration for multiple nodes

### ISSUE THREAD

**Issue by javieryanez** [VanRoy/spring-data-jest#113]
In a Jhipster project I need connect to a ElasticSearch multinode cluster. How can I do that?

With Spring Data ElasticSearch I used:

`spring.data.elasticsearch.cluster-nodes=node1:9300,node2:9300`

But something similar, like this:

`spring.data.jest.uri=http://node1:9200,node2:9200`

or

`spring.data.jest.uri=http://node1:9200,http://node2:9200`

doesn't work.

Is there any way to connect to multiple nodes?

**Comment by VanRoy** [comment]
Hi @javieryanez , the support of multiple node was introduced in Spring Data Jest 3.2.2.

And the new configuration key is : spring.data.jest.uri**s**

Do not hesitate to send me a feedback if it's don't work as expected with the 3.2.2.
Thanks.
Julien.

**Comment by javieryanez** [comment]
Hi @VanRoy ,

Thank you for you reply.

I haven't been able to prove it yet, but it's just what I needed.

**Comment by sylphir** [comment]
Hi @VanRoy ,
I tried the configuration for multiple nodes but unfortunately it does not really work as expected for an elasticsearch cluster ensuring high availability. 
There is no fail-over management if a node falls. 
So I created this PR : https://github.com/VanRoy/spring-data-jest/pull/114
to make it possible to configure the node discovery (https://github.com/searchbox-io/Jest/blob/master/jest/README.md#node-discovery-through-nodes-api) . 
I also added the default configuration of the scheme to be able to set https
