### ISSUE TITLE
Problem with ElasticsearchJestAWSAutoConfiguration

### ISSUE THREAD

**Issue by ryrob89** [VanRoy/spring-data-jest#115]
The new change to add:
@AutoConfigureAfter(
  name = {"org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration", "org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration"}
)

Does help to allow AWSCredentialsProvider to properly be configured if the project actually uses this dependency which includes both of those classes:
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-aws-autoconfigure</artifactId>
    </dependency>

When the project does not include that dependency there is an issue where this library always defaults to the US_WEST_2 region, because the constant value, DEFAULT_REGION,  from the aws sdk Regions.java file is used. 

Is it possible to allow a parameter region value to be set for the default region values used in this library? Additionally, setting up the AWSCredentialsProvider shouldn't require the spring-cloud-aws-autoconfigure artifact.

**Comment by VanRoy** [comment]
Hi @ryrob89 ,

There are this property : spring.data.jest.aws-region

Can you try it and tell me if it fix your issue ? 

Thanks.
Julien.

**Comment by ryrob89** [comment]
Hi @VanRoy ,

I did actually have that property set and it appears to have allowed the library to connect to the east region cluster, but the Spring SQS library continued to default to the west region. My hunch was that it had to do with falling back on the default region:
https://github.com/VanRoy/spring-data-jest/blob/master/spring-boot-starter-data-jest/src/main/java/com/github/vanroy/springboot/autoconfigure/data/jest/ElasticsearchJestAWSAutoConfiguration.java#L99

However, even when I created an instance of that bean to avoid it hitting that line of code, I still kept having issues with the SQS connection defaulting to the west region. I have another project with just the SQS Spring library being used without this library and the issue was not occurring.

Additionally, I was able to resolve the issue by pulling in this dependency into my pom:
spring-cloud-aws-autoconfigure
I believe that this resolved it, because ElasticsearchJestAWSAutoConfiguration.java requires two classes from that dependency for the AutoConfigureAfter annotation. The main issue, is that by pulling in that extra dependency I had to add additional properties to my .yml file to avoid some undesired auto configurations.

**Comment by VanRoy** [comment]
@ryrob89 , thanks a lot for the very detailled report.
Do you have the possibilty to send me a sample of your project to help me to reproduce the issue ?

**Comment by ryrob89** [comment]
@VanRoy Sure, give me a little bit of time and I will try to put together a small project that may be able to reproduce the issue.

**Comment by ryrob89** [comment]
It seems to be taking a bit longer than I expected to try to reproduce the issue in a smaller set of of code. I am going to close this issue and just utilize the spring-cloud-aws-autoconfigure dependency for now.

**Comment by VanRoy** [comment]
Ok @ryrob89 , dot not hesitate to re-open when you want.
Thanks.
