### ISSUE TITLE
Using RestController instead of CommandLineRunner for output

### ISSUE THREAD

**Issue by Priam123** [VanRoy/spring-data-jest#117]
Hello,

I understand the current project shows output on the command line. But how is it possible to create a REST API out of this instead? When I tried to go about, the server on 8080 hadn't even been started on application run. 
My application connects to the Amazon Managed Elasticsearch. So is it possible that since it connects to the Amazon ES URI, it overrides the localhost:8080 connection. Is there a way for me to use both?

**Comment by VanRoy** [comment]
Hi @Priam123 ,

SpringDataJest library is not specific to command line or REST API.
You can use SpringDataJest to any kind of application.

You can find a sample of how build  REST service with SpringBoot here : https://spring.io/guides/gs/rest-service/

At this sample, you can add the Elasticsearch implementation found in this sample : https://github.com/VanRoy/spring-data-jest/tree/master/spring-boot-sample-data-jest-aws
