### ISSUE TITLE
Query against _all instead of against entity index

### ISSUE THREAD

**Issue by karolherbst** [VanRoy/spring-data-jest#12]
the query argument is omitted here: https://github.com/VanRoy/spring-data-jest/blob/master/spring-data-jest/src/main/java/com/github/vanroy/springdata/jest/JestElasticsearchTemplate.java#L450

doesn't it have to be query instead of null? Currently the search query is made against _all/_search although the index name is known. I got to this situation by having a custom @Query on my Repository method.

**Comment by VanRoy** [comment]
Hi @karolherbst ,

Thank you for your feedback.
Indeed it's a bug.

Your fix it's good, i will add new unit test for check it later.

Thanks again for your help.
Julien.
