### ISSUE TITLE
Missing 3.2.3 tag / release

### ISSUE THREAD

**Issue by aheritier** [VanRoy/spring-data-jest#120]
Hi @VanRoy 

  It seems that you forgot to push the 3.2.3 tag and create a release for it.

https://github.com/VanRoy/spring-data-jest/releases
https://github.com/VanRoy/spring-data-jest/tags

Best regards

**Comment by VanRoy** [comment]
Indeed Arnaud, thanks for the notice :) 
It's fixed.
