### ISSUE TITLE
Does API handle transactions

### ISSUE THREAD

**Issue by aelmalki** [VanRoy/spring-data-jest#127]
I have a need with indexing to Elasticsearch after persist data to Database (sql for my exemple), when exception fired in the out of method during performing SQL commit (for constraint violation for example), the index is however added to Elasticsearch.

        @PostMapping(path = "/save")
        @Transactional
        public void save() {
                ElasticDocument doc = new ElasticDocument();
                doc.setNom("John");
                doc.setPrenom("Dark");
        
                mySqlRepository.save(doc);
                myElasticSearchRepository.save(doc);

                throw new RuntimeException("Testing transaction rollback");
            }

How could I assure that my service is atomic ?

Some part of my pom.xml : 

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.5.RELEASE</version>
	</parent>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-elasticsearch</artifactId>
		</dependency>

		<dependency>
			<groupId>com.github.vanroy</groupId>
			<artifactId>spring-boot-starter-data-jest</artifactId>
			<version>3.1.5.RELEASE</version>
		</dependency>
	</dependencies>

Thank you for your help.

**Comment by VanRoy** [comment]
Hi @aelmalki , unfortunaly Elasticsearch does not support transactions.
One option, is to save in ES after transaction success. For that you can use spring event management with the annotation @TransactionalEventListener.

Some docs : https://www.baeldung.com/spring-events

**Comment by aelmalki** [comment]
Thank you @VanRoy for your reply.
