### ISSUE TITLE
How to log Elasticsearch request and response with spring-data-jest

### ISSUE THREAD

**Issue by surjitsinghbhachu** [VanRoy/spring-data-jest#130]
I am using Spring Boot 2 with spring-data-jest 3.2.5 and want to log the request and responses to and from ElasticSearch. 

I tried setting the following parameter which didn't work. 

> logging.level.org.springframework.data.elasticsearch.core=DEBUG

Is there another property in spring-data-jest I can set to log the search requests/responses?

**Comment by VanRoy** [comment]
Hi @surjitsinghbhachu , Jest is based on Apache HTTP Client 4.x
You can try to confiure logging level as describe in this documentation : https://hc.apache.org/httpcomponents-client-4.5.x/logging.html

**Comment by surjitsinghbhachu** [comment]
Thanks @VanRoy 

I was able to log the requests using the following parameter in my Spring application.properties.

> logging.level.org.apache.http=DEBUG

**Comment by VanRoy** [comment]
:+1:
