### ISSUE TITLE
Save method doesn't seem to work, No error log

### ISSUE THREAD

**Issue by qracle** [VanRoy/spring-data-jest#131]
Recently, prod systems have been losing data frequently,  or the 'status' field has not changed.
I tracked the info log, the following:
![asd](https://user-images.githubusercontent.com/32318904/68863365-2e98ad00-072a-11ea-9636-3ffdd0fe52f6.png)
here is the code:
<img width="978" alt="34D7C3E1-B12C-4BA0-B091-BA98AAD57BE6" src="https://user-images.githubusercontent.com/32318904/68863183-d2ce2400-0729-11ea-9ebe-4a3675a0db63.png">
After the code is executed，I found the "txnStatus" was still the old value, instead of the expected value "1"
<img width="1417" alt="AFCD91B6-CC19-4CE2-98AC-DD337FE9FE6F" src="https://user-images.githubusercontent.com/32318904/68864137-91d70f00-072b-11ea-8844-df769232e8cf.png">
it seems the function "save" doesn't work, so could you please give me some suggestions? thank you

**Comment by VanRoy** [comment]
Hi @qracle , Can you tell me if this issue is new and come with an upgrade of SpringDataJest or if this save have never worked ?
Do you have some other ES repository that works well ?

Maybe you could activate the HTTP logs with this settings to help you to investigate : 
logging.level.org.apache.http=DEBUG

Keep me in touch.
Thanks.
Julien.

**Comment by qracle** [comment]
This problem has not been found before.If jest throws an exception, I can get some information in the error log.But the problem I described doesn't provide any error logs.So I'm very confused.

There are some ES repository seems work well.(At least yesterday's Numbers were accurate, I need to confirm)

The following is the release from the project, I never upgrade them：
- spring boot version: 2.1.4.RELEASE
- elasticsearch server version: 6.4.3 (Use Aws Elasticsearch Service)
- jest version: 6.3.1
- spring boot starter data jest version: 3.2.0.RELEASE

I will active the debug log to get more information, if there is any problem or progress, I will contact you in time.

**Comment by qracle** [comment]
This phenomenon is caused by concurrency. Thank you very much for your timely reply to my question.I will close this question.

**Comment by VanRoy** [comment]
Thanks for your feedback. I hope you can fix it quickly.

**Comment by qracle** [comment]
Hi Van,
    Because of this problem, I need to use Elasticsearch optimistic locks, I read your conversations in  #9 and #11.   
    Did spring data jest provided any annotations for the version control in 3.2.0.RELEASE? Or  I need to use @Version(JPA) or @JestVersion(Jest). 
    Looking forward to your reply. Thank you.

**Comment by VanRoy** [comment]
Hi @qracle , you can use @Version ( org.springframework.data.annotation ) .
