### ISSUE TITLE
Question: Is it possible to get the Client?

### ISSUE THREAD

**Issue by Ogniute** [VanRoy/spring-data-jest#132]
In out team we have the problem, that we have to insert a lot of data in a short time. For that we need to deactivate the refresh (set to -1) and the replicas (set to 0) in our job for a faster bulk insert/update operation. After the bulk we want to reset these settings and wait for a green status and switch the index for our queries. But therefore we need either the client or a function to do that.

**Comment by VanRoy** [comment]
Hi @Ogniute.
Sure, you can inject JestClient in your application.

**Comment by Ogniute** [comment]
I could have come up with that myself  🙈

**Comment by Ogniute** [comment]
worked for me
