### ISSUE TITLE
Add support for CollapseBuilder

### ISSUE THREAD

**Issue by castronu** [VanRoy/spring-data-jest#138]
JestElasticsearchTemplate doesn't support the collapse builder.
Please add something like:

if (searchQuery.getCollapseBuilder() != null) {
		    request.collapse(searchQuery.getCollapseBuilder());
        }

At the line: https://github.com/VanRoy/spring-data-jest/blob/a6597a345d5db4b7fea78fe572afd5d8fa633d65/spring-data-jest/src/main/java/com/github/vanroy/springdata/jest/JestElasticsearchTemplate.java#L1255

**Comment by VanRoy** [comment]
Fixed in release 3.3.2.RELASE
