### ISSUE TITLE
Version Release Request 2.1.2

### ISSUE THREAD

**Issue by karolherbst** [VanRoy/spring-data-jest#14]
We would like to use spring-data-jest in our productive code fairly soon and would like to get around deploying our own built inside our own repository, because we hard depend on 85b40ff0d12d880a6248906a6bcc4405ad7fa4b3 being there.

It is fine if there are no plans for it and have a later release, just good to know what the plans are.

**Comment by VanRoy** [comment]
Hi @karolherbst 

Release it's done but the number is 2.1.3.
I had doing a mistake on 2.1.2 creation, sorry for that.

Julien.

**Comment by karolherbst** [comment]
no worries, thanks a lot for the release
