### ISSUE TITLE
@DynamicTemplates is not supported

### ISSUE THREAD

**Issue by aheritier** [VanRoy/spring-data-jest#141]
Added in Spring Data ES 3.1.6 it is possible with `@DynamicTemplates` to configure at the entity level the dynamic_templates of ES used for the index without defining the full mapping with `@Mapping`

https://jira.spring.io/browse/DATAES-535
https://github.com/spring-projects/spring-data-elasticsearch/pull/238

The annotation is silently discarded

**Comment by VanRoy** [comment]
Hi @aheritier , thanks a lot for the feedback. I'll try to implement this annotation in the next minor version.

**Comment by aheritier** [comment]
Thanks a lot Julien

**Comment by VanRoy** [comment]
Hi @aheritier , It's fixed in release 3.3.2.RELASE

**Comment by aheritier** [comment]
awesome. thanks a lot @VanRoy
