### ISSUE TITLE
如何带密码访问es6.3.2，es安全插件x-pack

### ISSUE THREAD

**Issue by monkeylq** [VanRoy/spring-data-jest#146]

**Comment by monkeylq** [comment]
在项目中我参考了ElasticsearchJestAutoConfiguration重写了配置，但这是无效的，
Cannot execute jest action , response code : 401 , error : 401 Unauthorized , message : null

**Comment by monkeylq** [comment]
喔~，springdata elastic health check 也需要配置密码，这里要么关闭健康检查，要么重写elastic client（重写相当于jest和springdata elastic 两套配置....），兄弟们，我是否正确？有更好的方案吗，坐等~

**Comment by VanRoy** [comment]
hi @monkeylq Can you send me more details and more context of your issue ( stracketrace, version ,configuration ). Thanks.

**Comment by monkeylq** [comment]
> hi @monkeylq Can you send me more details and more context of your issue ( stracketrace, version ,configuration ). Thanks.
springboot config default is true
`
management.health.elasticsearch.enabled=false
`
这个配置是springBoot自带的es健康检查，默认使用 Spring Data Elasticsearch的 **transport**端口访问
我选择关闭这个健康检查
