### ISSUE TITLE
Plugins not loaded at startup

### ISSUE THREAD

**Issue by lordlothar99** [VanRoy/spring-data-jest#149]
Onlly package `org.elasticsearch.plugins` is scanned for plugins at startup in `com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestAutoConfiguration#scanPlugins`.
--> even though Expression-lang (`org.elasticsearch.script.expression.ExpressionPlugin`) and Painless-lang (`org.elasticsearch.painless.PainlessPlugin`) are in the classpath, they're not loaded.

**Comment by VanRoy** [comment]
@lordlothar99 It's released in 3.3.4.RELEASE. Thanks for your contribution.
