### ISSUE TITLE
A way to filter _source with include/exclude columns lists

### ISSUE THREAD

**Issue by dazewell** [VanRoy/spring-data-jest#15]
I'd like to specify which columns to include/exclude from the document.

Right now your implementation has the only way to filter _source document specifying "fields", but it's not a common case.

Interface of `Query` class allows to specify includes/excludes, but it's not taken into account right now,

The right way to do such type of filtering is to use `SearchSourceBuilder#fetchSource` method. The list of included/excluded columns is available via `NativeSearchQuery#getSourceFilter#getIncludes` e.g.

Of course it must be supported on the HTTP request level too and it'd be great to have this feature supported.

**Comment by VanRoy** [comment]
Hi @dazewell Thanks for your feedback.
 
Indeed it's not working actually and the tests is not written correctly.
I will merge the PR of @igelbox quickly.

**Comment by VanRoy** [comment]
@dazewell @igelbox Fix included in the release 2.1.4 available right now.
Thanks again for your help.
