### ISSUE TITLE
Java8 ZoneDateTime

### ISSUE THREAD

**Issue by mluckenbill** [VanRoy/spring-data-jest#20]
Hello, 

I have entities that include the Java8 ZoneDatetime and when I use your JEST libarary. It throws jackson serialization errors. I was wondering have you had any luck with Java 8 DateTime methods?

**Comment by mluckenbill** [comment]
om.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class java.time.ZonedDateTime]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)

**Comment by dkbrummitt** [comment]
I think the solution can be found here: http://palashray.com/jackson-handle-localdate-for-json/
I will tinker with this over the weekend, and if I can get it working, will submit a pull request.

**Comment by aminmc** [comment]
Just pass in the custom object mapper into your configuration. For example:

```
@Autowired
private ObjectMapper myCustomObjectMapper;

 @Bean
    public EntityMapper entityMapper() {
        return new EntityMapper() {
            @Override
            public String mapToString(Object object) throws IOException {
                return myCustomObjectMapper.writeValueAsString(object);
            }

            @Override
            public <T> T mapToObject(String source, Class<T> clazz) throws IOException {
                return myCustomObjectMapper.readValue(source, clazz);
            }
        };
    }

  @Bean
        @Primary
        public ElasticsearchOperations elasticsearchTemplate(JestClient jestClient) {
            return new JestElasticsearchTemplate(jestClient, new DefaultJestResultsMapper(entityMapper));
        }
```
I have entities that use java 8 localdatetime

**Comment by VanRoy** [comment]
Hi @mluckenbill , can you tell me if the @aminmc solution fixed your problem and if we can close this issue ? 

Thanks.

**Comment by mluckenbill** [comment]
Hello @VanRoy and @aminmc I'll take a look shortly.
