### ISSUE TITLE
public <T> T query(SearchQuery query, ResultsExtractor<T> resultsExtractor) throws Unsupported operation

### ISSUE THREAD

**Issue by aminmc** [VanRoy/spring-data-jest#23]
Hi 
I'm using the following method from ElasticsearchOperations:

```
public <T> T query(SearchQuery query, ResultsExtractor<T> resultsExtractor)
```
However this method throws UnsupportedOperation.  I presume I should be using from JestElasticsearchTemplate the following:

```
public <T> T query(SearchQuery query, JestResultsExtractor<T> resultsExtractor)
``` 
The issue is now I have to customise my code to be able to distinguish between Jest/Non Jest implementation of ElasticsearchOperations.  I'd like to be able to use the elastic search operations class and use configuration to swap the implementation from using JEST to local without the need to customise my code to use Jest implementation of results extractor.  I've not used Jest before so I'm not sure if it's possible to use the existing interface from Elasticsearch Operations.

Thanks

**Comment by VanRoy** [comment]
Hi @aminmc ,

Indeed the signature with ResultsExtractor is not available on spring-data-jest.
It's not possible to implement it because Jest not return result with the same format.

So, you need to use signature with JestResultsExtractor.

I hope this will help you.

**Comment by aminmc** [comment]
thanks @VanRoy I'll have to update my code.
