### ISSUE TITLE
When ES response is not 200, DefaultJestResultsMapper throws NPE

### ISSUE THREAD

**Issue by kozayur-uptake** [VanRoy/spring-data-jest#27]
When ES response is not 200, DefaultJestResultsMapper throws NPE trying to parse it into a result. I would like to see some exception thrown by the JestElasticsearchTemplate that contains an Http status code and the message from the Elastic search.

**Comment by VanRoy** [comment]
Hi @kozayur-uptake , thanks for your feedback.

Can you send me some code snippets to reproduce this issue ?

Julien.

**Comment by kozayur-uptake** [comment]
Sure, just create a match query to ES for the field that does not exist in
your document.

**Comment by VanRoy** [comment]
Fixed in release 2.3.1
