### ISSUE TITLE
ES on standalone server 

### ISSUE THREAD

**Issue by jayeshgangadharan** [VanRoy/spring-data-jest#28]
@VanRoy Can spring-data-jest work without AWS related classes/jars, dependencies?

I've Elasticsearch running in my environment (not AWS) and trying to use spring-data-jest but i keep getting AWS related errors. 

like this.
Bean method 'regionFromEC2' not loaded because @ConditionalOnClass did not find required class 'vc.inreach.aws.request.AWSSigner'

Is there a way i can disable AWS lookup by any chance? any help is much appreciated

**Comment by VanRoy** [comment]
Hi @jayeshgangadharan , It totally compatible with ES out of AWS.

In this case you don't add aws-signer dependency.
You can see a sample of standalone ES in this project : https://github.com/VanRoy/spring-data-jest/tree/master/spring-boot-sample-data-jest

Keep me in touch, if you need more help.

Julien.

**Comment by jayeshgangadharan** [comment]
ok great. i missed looking up your sample project earlier. Thanks @VanRoy
