### ISSUE TITLE
ElasticsearchExceptions bubbled during execute() are not useful

### ISSUE THREAD

**Issue by dshefchik** [VanRoy/spring-data-jest#29]
When internal execute() receives a response other than a 404 or < 200, it generates this custom error string with the underlying errors embedded inside. However, these real ES errors are actually super useful, detailed and formatted JSON, which would be nice to be able to access them without doing messy string parsing. 

Maybe instead of throwing a custom Exception in these cases we can just set the JestResult as failed and pass it back as-is? This would allow the caller to be flexible in how to handle the error.

**Comment by VanRoy** [comment]
Hi @dshefchik , it's a good idea.

I will investigate to implement this feature.

Thanks for your feedback.
Julien.

**Comment by VanRoy** [comment]
This feature is implemented in the next release 3.0.0. Can you try the 3.0.0-SNAPSHOT and give me some feedback ?

Thanks.
Julien.
