### ISSUE TITLE
Individual index request expects @Document entity

### ISSUE THREAD

**Issue by stevenhurth** [VanRoy/spring-data-jest#3]
When calling the individual index() method, an object or source is expected to be on the IndexQuery. If the object is set, but is not a @Document entity, we get an assertion failure.

I am able to work around this by using the bulkIndex() operation.

I would suggest that the index() method check if the object is of @Document before trying to set the entity id.

```
@Override
public String index(IndexQuery query) {
	String documentId = execute(prepareIndex(query)).getId();

	// We should call this for document entities because we are not going through a mapper.
	if (query.getObject() != null && isDocument(query.getObject().getClass())) {
		setPersistentEntityId(query.getObject(), documentId);
	}
	return documentId;
}
```

**Comment by VanRoy** [comment]
@stevenhurth, thanks for your feedback.

After some tests, it's seem to be the same behavior on  spring-data-elasticsearch.
The goal of spring-data-jest is to be more closest as possible of spring-data-elasticsearch behavior.

Please tell me if you can doing your expected with spring-data-elasticsearch, i will investigate more deeply.

Thanks a lot.
Julien.

**Comment by stevenhurth** [comment]
It is definitely the same issue with the spring-data-elasticsearch. Although, I am thinking it's a bug.

When the IndexRequestBuilder is prepared, it checks to see if the object is a @Document entity to pull the id from. So, one would think that it would be checked again when trying to set the id onto the object as well.

Using the object property on the index request would be nice, because it serializes the json for us. However, we can just build the json ourselves and set it in the source property of the IndexQuery.

**Comment by VanRoy** [comment]
@stevenhurth , Thanks for your investigation.

I will fix it in the next version.

Julien.
