### ISSUE TITLE
Is there a way to customize JSON serialization?

### ISSUE THREAD

**Issue by robmoore** [VanRoy/spring-data-jest#32]
Looking at the Spring project, it looks like customizing JSON serialization simply requires registering the entity manager with the Elasticsearch template (https://github.com/spring-projects/spring-data-elasticsearch/wiki/Custom-ObjectMapper). I don't see any way to specify an entity manager in the JestElasticsearchTemplate implementation. 

The issue I'm having is that I have a number of Joda date objects that I'd like to have serialized as simple strings rather than the full set of fields in the Joda objects. I don't see any way to specify that I want to use different de/serializers for given types. Is there any means to accomplish this today?

**Comment by robmoore** [comment]
Looking at this a bit more, it seems I can accomplish the same thing by passing in the entity mapper as an argument to the JestResultsMapper like so:

```
    @Bean
    public EntityMapper entityMapper() {
        return new CustomEntityMapper();
    }

    @Bean
    public JestElasticsearchTemplate elasticsearchTemplate(JestClient jestClient) {
        return new JestElasticsearchTemplate(jestClient, new DefaultJestResultsMapper(entityMapper()));
    }
```

**Comment by VanRoy** [comment]
Hi @robmoore , thanks for your feedback. Your solution working ?

**Comment by robmoore** [comment]
@VanRoy It seems to be working although I'm kind of surprised given the that it's a results mapper which seems like the deserialization side of the equation. 

Can you confirm that there's not another approach you would recommend instead?

**Comment by VanRoy** [comment]
Hi @robmoore , indeed the entityMapper in DefaultJestResultsMapper is actually used for serialization and deserialization.
Thanks for your feeback.
Julien.
