### ISSUE TITLE
How can i provide aws access key to JestTemplate?

### ISSUE THREAD

**Issue by jayeshgangadharan** [VanRoy/spring-data-jest#34]
I have my aws elasticsearch service secured by aws iam user under access policies. how do i provide the access key on my request to aws?

**Comment by MrMoner** [comment]
This is a question on AWS and not spring-data-jest.

I suggest you have a look at AWS IAM roles and security groups.

**Comment by jayeshgangadharan** [comment]
@MrMoner I see the page https://github.com/VanRoy/spring-data-jest has aws signing interceptor dependency but not sure how to set my credentials ?

**Comment by aminmc** [comment]
I'd recommend looking at: 
https://github.com/VanRoy/spring-data-jest/tree/master/spring-boot-sample-data-jest-aws

The aws signing interceptor looks at certain environment variables.  For example:
AWS_SECRET_KEY=XXXX
AWS_ACCESS_KEY_ID=XXXX

**Comment by jayeshgangadharan** [comment]
Thanks @aminmc

**Comment by aminmc** [comment]
@jayeshgangadharan I needed to customise the object mapper for my stuff but the code looks like this:

``` @Configuration
    public class AWSConfig {

        @Bean
        @Primary
        public AWSCredentialsProvider awsCredentialsProvider() {
            return new DefaultAWSCredentialsProviderChain();
        }


        @Autowired
        private EntityMapper entityMapper;

        @Bean
        @Primary
        public ElasticsearchOperations elasticsearchTemplate(JestClient jestClient) {
            return new JestElasticsearchTemplate(jestClient, new DefaultJestResultsMapper(entityMapper));
        }

    }```

**Comment by jayeshgangadharan** [comment]
Got it. I will add the credentialsprovider to my config and follow this documentation http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html.

Thank you @aminmc

**Comment by aminmc** [comment]
No worries. I'm not sure if you're able to close this issue in that case but if you can then please do. Cheers.
