### ISSUE TITLE
Read timeout

### ISSUE THREAD

**Issue by therealmark** [VanRoy/spring-data-jest#37]
When deploying to aws, I'm getting a read timeout. Is it possible to configure this in my application.properties file?

**Comment by aminmc** [comment]
You can override read timeout using the following:
```
spring.data.jest.read-timeout
```
In version 3.x you will be able to define custom HttpClientConfigBuilderCustomizer for updating the underlying HTTP client.

**Comment by therealmark** [comment]
Thanks!!
