### ISSUE TITLE
NullPointerException when MultiDocumentResult return found: false

### ISSUE THREAD

**Issue by matfury** [VanRoy/spring-data-jest#42]
Getting an NPE from:
com.github.vanroy.springdata.jest.internal.MultiDocumentResult

Line 60:
```
public String getSource() {
	return jsonObject.get("_source").toString();
}
```
The json doesn't have _source which seems normal for a returned multidocument.
{"_index":"coi-api-test","_type":"metricKeyword","_id":"153-307413","found":false}

When the jsonObject tries to get the _source it returns null thus it then throws an NPE.
This happens when I pass a collection of ID's to findAll in the repository.
Happening in both versions 2.2.0.RELEASE and 2.3.1.RELEASE
Thanks

**Comment by VanRoy** [comment]
@matfury Issue fix and released on 2.3.2.RELEASE.

Thanks for your feedback.
