### ISSUE TITLE
Question: How to build a query with multiple filters?

### ISSUE THREAD

**Issue by mancini0** [VanRoy/spring-data-jest#50]

**Comment by mancini0** [comment]
Disregard, I was using termQuery() when I should've been using term**s**Query
queryBuilder.withFilter(boolQuery().must(termsQuery(param.getKey(),param.getValue())));

**Comment by VanRoy** [comment]
Hi @mancini0 ,

Can you send me some more details or sample code ?

**Comment by VanRoy** [comment]
Hi @mancini0 , do you have some news about this question ?

**Comment by mancini0** [comment]
Hello, I was able to achieve the desired functionality by using a Criteria object:

 Criteria criteria = null;
            for (Map.Entry<String,String> param : allRequestParams.entrySet()){
                if(criteria==null){
                    criteria = new Criteria(param.getKey()).is(param.getValue());
                }
                else{
                    criteria.and(new Criteria(param.getKey()).is(param.getValue()));
                }
            }
