### ISSUE TITLE
Application uses embedded ES instead of AWS

### ISSUE THREAD

**Issue by nenadkitanovic89** [VanRoy/spring-data-jest#51]
Hi,
When I start the application it starts and uses the embedded ES instead of AWS ES. I have 
  spring.data.jest.uri = search-es-xxxxxxxxxxxxxxxxxxx.us-west-1.es.amazonaws.com property and dependencies:
    compile group: 'com.github.vanroy', name: 'spring-data-jest', version: '2.1.4.RELEASE'
    compile group: 'vc.inreach.aws', name: 'aws-signing-request-interceptor', version: '0.0.15'

Tried with other versions too, but it still starts embedded ES and uses it instead of AWS one.

This is the output during startup (obviously uses local es):

_2018.01.06;23:36:11 [main] INFO  org.elasticsearch.node  - [Dittomaster] version[1.5.2], pid[29078], build[62ff986/2015-04-27T09:21:06Z]
2018.01.06;23:36:11 [main] INFO  org.elasticsearch.node  - [Dittomaster] initializing ...
2018.01.06;23:36:11 [main] INFO  org.elasticsearch.plugins  - [Dittomaster] loaded [], sites []
2018.01.06;23:36:12 [main] INFO  org.elasticsearch.node  - [Dittomaster] initialized
2018.01.06;23:36:12 [main] INFO  org.elasticsearch.node  - [Dittomaster] starting ...
2018.01.06;23:36:12 [main] INFO  org.elasticsearch.transport  - [Dittomaster] bound_address {local[1]}, publish_address {local[1]}
2018.01.06;23:36:12 [main] INFO  org.elasticsearch.discovery  - [Dittomaster] elasticsearch/xYLpfI7nRxqX5Xyxr4gNGw_

Do you have any ideas?
Best Regards,
Nenad

**Comment by VanRoy** [comment]
Hi @nenadkitanovic89 ,

Are you sure that your property 'spring.data.jest.uri' is really applied ?
The embedded ES start only if 'spring.data.jest.uri' is not present or empty.

You can check with a breakpoint at this line : 
https://github.com/VanRoy/spring-data-jest/blob/master/spring-boot-starter-data-jest/src/main/java/com/github/vanroy/springboot/autoconfigure/data/jest/ElasticsearchJestAutoConfiguration.java#L79

Keep me in touch if you can not fix your issue.
Thanks.
Julien.

**Comment by nenadkitanovic89** [comment]
@VanRoy 

Thank you for your quick response. I have debugged the code and I noticed that first the embedded server is started and after that the breakpoint stops on the line you mentioned (if (StringUtils.isEmpty(properties.getUri())) {). And the properties.getUri has a proper value.

This is a bit weird.... And later the operations are performed on embedded es and not the aws one.

I'm using the ElasticsearchRepository. Is this supported by jest client?

Best Regards,
Nenad

**Comment by VanRoy** [comment]
Hi @nenadkitanovic89 ,

Have you added this on your SpringApplication class :

@SpringBootApplication(exclude = {ElasticsearchAutoConfiguration.class, ElasticsearchDataAutoConfiguration.class})

You can see sample here : https://github.com/VanRoy/spring-data-jest/blob/master/spring-boot-sample-data-jest-aws/src/main/java/sample/data/jest/aws/SampleJestApplication.java

And documentation on README  :)

**Comment by VanRoy** [comment]
Hi @nenadkitanovic89 , do you have found fix for your issue ?
