### ISSUE TITLE
better conf properties ( port and embedded)

### ISSUE THREAD

**Issue by sarahBuisson** [VanRoy/spring-data-jest#53]
Hy, can you add a properties so we can choose on which  port the embedded elasticsearch created by createInternalNode() will be? also, an you add a boolean to allow /disable the createInternalNode, instead of just checking the presence of jest.uri?

**Comment by VanRoy** [comment]
Hi @sarahBuisson , It's a good idea for improvement.

Can you try to propose a PR with this improvements ? 

Thanks for your feedback and your help.
Julien.

**Comment by irsath** [comment]
Hello @sarahBuisson, actually you can already define a custom port.

In your application.yml, juste put this : 
`spring:
  data:
    elasticsearch:
      properties:
        # Home directory of the embedded Elasticsearch instance.
        # Default to the current working directory.
        path:
          home: target/elastic
        # HTTP Port of in memory elastic search instance
        http:
          port: 5555`

In fact `ElasticsearchJestAutoConfiguration.createInternalNode()` is filling the in-memory cluster setting by whatever settings is on `ElasticsearchProperties` like so : 
`int port = SocketUtils.findAvailableTcpPort();
		String clusterName = INTERNAL_TEST_CLUSTER_NAME + UUID.randomUUID();

		Settings.Builder settingsBuilder = Settings.builder()
				.put("cluster.name", clusterName)
				.put("http.type", "netty4")
				.put("http.port", String.valueOf(port));

		if (this.esNodeproperties != null) {
			this.esNodeproperties.getProperties().forEach(settingsBuilder::put);
		}`

As the settings object use a map internally, if you redefine the `http.port` in your properties, it will redefine it in your map.
