### ISSUE TITLE
[QUESTION] Possible to isolate Spring Boot Requirement

### ISSUE THREAD

**Issue by jordanbaucke** [VanRoy/spring-data-jest#54]
I am trying to get `Spring Data Jest 3.0.0.RELEASE` working w/ an application that is primarily running `Spring Boot 1.5.10.RELEASE`, since `Spring Data Jest 3.0.0.RELEASE` requires `Spring Boot 2.0.0M4`, I'm wondering if you know if I can isolate the dependency for `Spring Boot 2.0.0M4` to just apply to Spring Data Jest in gradle or maven? 

Thanks

**Comment by VanRoy** [comment]
Hi @jordanbaucke , unfortunately it's not possible. Spring Data Jest 3.x is based on Spring Data Commons 2.x that is dependent of Spring 5.x that is only compatible with Spring Boot 2.

Sorry. it's as requirement of Spring Data projects not specific to Spring Data Jest.
