### ISSUE TITLE
Elasticsearch 6.2.2

### ISSUE THREAD

**Issue by tfeiner** [VanRoy/spring-data-jest#55]
Hi!
Are there plans to upgrade to ES 6.2.x?

**Comment by VanRoy** [comment]
Hi @tfeiner ,

Do you seen any issues with ES 6.2 ?
When using Jest they are many chances that the more recent version of Elasticsearch should work.

More generally spring-data-jest is aligned to spring-data-elasticsearch dependencies.

**Comment by aheritier** [comment]
It seems to work in remote but the main issue is that the internal node doesn't work anymore for tests by exemple. It was removed in 6.x
https://discuss.elastic.co/t/no-more-local-transport-on-6-0-x/102416

**Comment by VanRoy** [comment]
Hi @aheritier , thanks for your your feedback and your interest.

Indeed I believe that there are no plan to support any kind of embedded node in next versions of ES.
Maybe the best workaround is to use docker or embedded ES solutions to launch ES before tests.  
Some useful links that you surely already know :

- https://github.com/dadoonet/testcontainers-java-module-elasticsearch
- https://github.com/allegro/embedded-elasticsearch
- https://github.com/avast/gradle-docker-compose-plugin

I will investigate to provide some new samples with theses solutions.

**Comment by aheritier** [comment]
Hi @VanRoy 

yes using docker containers (hello @dadoonet) is a solution but it seems that ES also provide some dedicated test frameworks ( https://www.elastic.co/guide/en/elasticsearch/reference/current/using-elasticsearch-test-classes.html ) which could avoid to have the prerequisite to have docker installed and running. I will have a look at this.

**Comment by dadoonet** [comment]
Thanks @aheritier for the ping.
@VanRoy I wrote a sample test project here that might be useful: https://github.com/dadoonet/elasticsearch-integration-tests/tree/05-cloud

HTH

**Comment by VanRoy** [comment]
@dadoonet Thanks a lot for your help. I will integrate this in my samples.

@aheritier , I already tried to use ESIntegTestCase provided by ES but I don't really like the obligation to extend this class in my tests it often enter in conflit with own extend.
Another issue, I beleive that some modules are mocked in ESIntegTest and not really reproduce the real behaviors.

@dadoonet In your opinion, what is the best option to use between ESIntegTestCase and Docker in our case ?

**Comment by dadoonet** [comment]
I'm only using `ESIntegTestCase` in the context of writing an elasticsearch plugin. Otherwise as a client user, I prefer using other strategies such as the Docker one.

So in your context, I'd use Docker.

The cons of it is that it requires Docker.

**Comment by aheritier** [comment]
@VanRoy yes just tested ESIntegTestCase and co and I don't like the approach too. Not really compatible with Spring.

What I would like is to start an ES node (or small cluster with a JUnit Rule like it's done in MockServer http://www.mock-server.com/mock_server/running_mock_server.html#junit_rule

Docker is an heavy requirement, on the developer environment but also on your CI system ..

**Comment by dadoonet** [comment]
> Docker is an heavy requirement, on the developer environment but also on your CI system ..

True. That's why in my demo project (You can see a french video of the talk I gave at Devoxx FR 2018: https://www.youtube.com/watch?v=ex2jS3GTUfk - have you heard about Devoxx FR @aheritier? 🤣), I'm detecting if something is yet running and if so, I'm just skipping the Docker container creation.

Handy if you started manually a local instance of elasticsearch or if you are using https://cloud.elastic.co Elasticsearch as a Service or ECE (Elastic Cloud Enterprise) where you can have an instance ready somewhere for your tests.

One of the thing I did not fix yet in this demo project is with fabric8 plugin. I'm always starting a container from maven even though elasticsearch is yet running at a given address (local, cloud, ...) which I should skip instead. If you find how to do it (I did not check TBH), please tell! ;)

**Comment by VanRoy** [comment]
@aheritier Do you have already tried embedded-elasticsearch ? It can be match with your needs ?
Previously I have used embedded-mongodb and it works well on local and CI. I suppose that embedded-elasticsearch too.

**Comment by aheritier** [comment]
@dadoonet yes it's a good approach. I will have a look at embedded-elasticsearch more closely. Let's not pollute more this case :-)

@VanRoy About the topic here and the compat with 6.x the "removal" of the NodeBuilder doesn't impact you too much (You already used Node by extended it) but the problems are:

1/ `transport.type=local` isn't supported any more and has to be [removed here](https://github.com/VanRoy/spring-data-jest/blob/master/spring-boot-starter-data-jest/src/main/java/com/github/vanroy/springboot/autoconfigure/data/jest/ElasticsearchJestAutoConfiguration.java#L154)

2/ `Settings.Builder` doesn't have anymore a put(Properties) method thus [here](https://github.com/VanRoy/spring-data-jest/blob/master/spring-boot-starter-data-jest/src/main/java/com/github/vanroy/springboot/autoconfigure/data/jest/ElasticsearchJestAutoConfiguration.java#L159) you have to use a loop like

```
            for (Map.Entry<String,String> entry: this.esNodeproperties.getProperties().entrySet()) {
                settingsBuilder.put(entry.getKey(),entry.getValue());
            }
```

3/ The MappingBuilder [is using by default](https://github.com/VanRoy/spring-data-jest/blob/master/spring-data-jest/src/main/java/com/github/vanroy/springdata/jest/MappingBuilder.java#L229) `index=not_analyzed` for the ID which isn't supported anymore in 6.x

**Comment by VanRoy** [comment]
@vivekranjan92 , I waiting for release 3.1 of SpringDataElasticsearch to finalize the 3.2 version of SpringDataJest that support ES 6.2.2.

**Comment by DanielFran** [comment]
@VanRoy 
Spring-data Lovelace GA is expect September 19th: https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Lovelace

Spring-boot 2.1.0.M3 is already targeting ElasticSearch 6.4.0 (https://github.com/spring-projects/spring-boot/issues/14384) and Jest 6.3.1 (https://github.com/spring-projects/spring-boot/issues/14429)

Actually Spring-boot 2.1.0 milestone is:
- 2.1.0.RC1: October 15, 2018
- 2.1.0: October 29, 2018

Are you planning any 3.2.0.RC version soon?
Maybe you could align your milestone with spring-boot?

**Comment by VanRoy** [comment]
Hi @DanielFran , yes it's planned soon after SpringData Lovelace relase.
I had started work here : https://github.com/VanRoy/spring-data-jest/tree/es-6.x

**Comment by DanielFran** [comment]
@VanRoy Lovelace release has been changed to September 21th.

**Comment by DanielFran** [comment]
@VanRoy any news about a new version targeting ES 6?

**Comment by VanRoy** [comment]
Hi @DanielFran , the version is ready on es-6.x branch.
Do you have the possibility to test this version before I release it ?
I plan to release it in same time of Spring Boot 2.1.0.

Thanks.
Julien.

**Comment by VanRoy** [comment]
Hi @gauravbrills, it's released. The new version if 3.2.0.RELEASE.
Please feel free to feedback if you detect some issues.
Thanks.

**Comment by gauravbrills** [comment]
@VanRoy ya was trying a upgrade but seems a stage check the new data version is doing for non reactive projects . I think it makes sense but they shouldn't do if I have exposed my custom repository methods in another interface raised this https://github.com/spring-projects/spring-boot/issues/15356
