### ISSUE TITLE
Using @EnableElasticsearchRepositories

### ISSUE THREAD

**Issue by ghahramani** [VanRoy/spring-data-jest#57]
Hi,

Do you have any plan to use @EnableElasticsearchRepositories annotation to split elasticsearch repositories from other spring data module?

Currently, it does not work with MongoReactive spring data, it detects Mongo repositories as elasticsearch

**Comment by VanRoy** [comment]
Hi @ghahramani ,

Normally it should be work. SpringDataJest just extend SpringDataES.

Do you have tried with SpringDataES ? 
Can you send me small sample of your project ?

Julien.

**Comment by ghahramani** [comment]
My mistake. This is invalid issue. I had to configure JestTemplate. The problem was in starting-up, it shows error but with WARN level about wrong format of date, so I couldn't figure out what was the problem. I fixed it with this.

```
@Bean
fun elasticsearchTemplate(client: JestClient, converter: ElasticsearchConverter, builder: Jackson2ObjectMapperBuilder): JestElasticsearchTemplate {
	val entityMapper = CustomEntityMapper(builder.createXmlMapper(false).build())
	val mapper = DefaultJestResultsMapper(converter.mappingContext, entityMapper)
	return JestElasticsearchTemplate(client, mapper)
}

inner class CustomEntityMapper(private val objectMapper: ObjectMapper) : EntityMapper {

	init {
		objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
		objectMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)
	}

	@Throws(IOException::class)
	override fun mapToString(`object`: Any): String {
		return objectMapper.writeValueAsString(`object`)
	}

	@Throws(IOException::class)
	override fun <T> mapToObject(source: String, clazz: Class<T>): T {
		return objectMapper.readValue(source, clazz)
	}
}
```

**Comment by VanRoy** [comment]
@ghahramani great.
