### ISSUE TITLE
Spring data Jest version and Amazon ES versions, correlation between them

### ISSUE THREAD

**Issue by jlarroque** [VanRoy/spring-data-jest#60]
Hi everyone!

I'm trying to use Spring data Jest in order to interact with an Amazon ES cluster. Right now, 18/04/2018, Amazon documentation says that the available versions of ES are "6.2, 6.0, 5.5, 5.3, 5.1, 2.3, and 1.5".

According to Spring Data Jest documentation, the ES supported versions are "1.5.2, 2.2.0, 2.4.3, 2.4.4, and 5.5.0".

So this means that I'm only capable of using Spring Data Jest library on ES 1.5 and 5.5.0? This ones are the only match that I see but perhaps I'm missing something.

**Comment by umesh936** [comment]
I interpreted the same and working with ES 5.5

**Comment by jlarroque** [comment]
Hi, I had a problem with 5.5, but I lost the link. It was a problem related to another spring library, and it was reported to Spring team but it didn't have a solution yet. I finally switched to the low level rest client, because I couldn't sort out that problem. Thank you for your concern

**Comment by VanRoy** [comment]
Ok @jlarroque , thanks.
