### ISSUE TITLE
path.home is not configured

### ISSUE THREAD

**Issue by umesh936** [VanRoy/spring-data-jest#61]
Hi @VanRoy I am using this with AWS ES. and i am getting exception

`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.searchbox.client.JestClient]: Factory method 'testClient' threw exception; nested exception is java.lang.IllegalStateException: path.home is not configured
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	... 37 more
Caused by: java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:128)
	at org.elasticsearch.env.Environment.<init>(Environment.java:118)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:90)
	at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:73)
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestAutoConfiguration$InternalNode.<init>(ElasticsearchJestAutoConfiguration.java:197)
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestAutoConfiguration.createInternalNode(ElasticsearchJestAutoConfiguration.java:165)
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestAutoConfiguration.testClient(ElasticsearchJestAutoConfiguration.java:80)
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestAutoConfiguration$$EnhancerBySpringCGLIB$$282f3ed2.CGLIB$testClient$2(<generated>)
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestAutoConfiguration$$EnhancerBySpringCGLIB$$282f3ed2$$FastClassBySpringCGLIB$$f2afb388.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at com.github.vanroy.springboot.autoconfigure.data.jest.ElasticsearchJestAutoConfiguration$$EnhancerBySpringCGLIB$$282f3ed2.testClient(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 38 more`

I am overriding the DefaultResultMapper to update the version property. So,  my configurations are 

<pre>
@Configuration
public class ElasticSearchConfiguration {
	@Autowired
	private JestClient client;
	@Bean
	public JestElasticsearchTemplate elasticsearchTemplate(JestClient jestClient) {
		return new JestElasticsearchTemplate(jestClient, new ExtendedResultMapper(new DefaultEntityMapper()));
	}
</pre>
Under pom.xml
<pre>
&lt;parent&gt;
		&lt;groupId&gt;org.springframework.boot&lt;/groupId&gt;
		&lt;artifactId&gt;spring-boot-starter-parent&lt;/artifactId&gt;
		&lt;version&gt;2.0.1.RELEASE&lt;/version&gt;
		&lt;relativePath /&gt; &lt;!-- lookup parent from repository --&gt;
	&lt;parent&gt;
</pre>

<pre>
&lt;dependency&gt;
			&lt;groupId&gt;com.github.vanroy&lt;/groupId&gt;
			&lt;artifactId&gt;spring-boot-starter-data-jest&lt;/artifactId&gt;
			&lt;version&gt;3.0.0.RELEASE&lt;/version&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;vc.inreach.aws&lt;/groupId&gt;
			&lt;artifactId&gt;aws-signing-request-interceptor&lt;/artifactId&gt;
			&lt;version&gt;0.0.16&lt;/version&gt;
			&lt;exclusions&gt;
				&lt;exclusion&gt;
					&lt;groupId>com.amazonaws&lt;/groupId&gt;
					&lt;artifactId&gt;*&lt;/artifactId&gt;
				&lt;/exclusion&gt;
			&lt;/exclusions&gt;
		&lt;/dependency&gt;
		&lt;dependency&gt;
			&lt;groupId&gt;org.springframework.cloud&lt;/groupId&gt;
			&lt;artifactId&gt;spring-cloud-aws-autoconfigure&lt;/artifactId&gt;
		&lt;/dependency&gt;
</pre>

Not able to figure out where I am doing wrong. Any hint or guidance will appreciated.

**Comment by umesh936** [comment]
Hi @VanRoy  Yes I have already excluded the mentioned configuration. But **uris**'s guess was bang on target. Thanks for this. It solve my problem.  I need to store the version with each object saving. So i created Extended Mapper But it doesn't seems to be working for me. Not sure what I have done wrong in code.
`public class ExtendedResultMapper extends DefaultJestResultsMapper {

	protected MappingContext<? extends ElasticsearchPersistentEntity<?>, ElasticsearchPersistentProperty> mappingContext;
	protected EntityMapper entityMapper;

	public ExtendedResultMapper(
			MappingContext<? extends ElasticsearchPersistentEntity<?>, ElasticsearchPersistentProperty> mappingContext) {
		super(mappingContext);
		this.mappingContext = mappingContext;
	}

	public ExtendedResultMapper(EntityMapper entityMapper) {
		super(entityMapper);
		this.entityMapper = entityMapper;
	}

	@Override
	public <T> T mapResult(DocumentResult response, Class<T> clazz) {
		T result = super.mapResult(response, clazz);
		if (result != null) {
			setPersistentEntityVersion(result, response.getVersion(), clazz);
		}
		return result;
	}

	@Override
	public <T> LinkedList<T> mapResults(MultiDocumentResult responses, Class<T> clazz) {
		LinkedList<T> results = super.mapResults(responses, clazz);
		if (results != null) {
			for (int i = 0; i < results.size(); i++) {
				setPersistentEntityVersion(results.get(i), getVersionOfDocument(i, responses), clazz);
			}
		}
		return results;
	}

	private <T> void setPersistentEntityVersion(T result, Long version, Class<T> clazz) {
		if (mappingContext != null && clazz.isAnnotationPresent(Document.class)) {
			PersistentProperty<ElasticsearchPersistentProperty> versionProperty = mappingContext
					.getPersistentEntity(clazz).getVersionProperty();
			if (versionProperty != null && versionProperty.getType().isAssignableFrom(Long.class)) {
				Method setter = versionProperty.getSetter();
				if (setter != null) {
					try {
						setter.invoke(result, version);
					} catch (Throwable t) {
						t.printStackTrace();
					}
				}
			}
		}
	}

	private Long getVersionOfDocument(int i, MultiDocumentResult responses) {
		for (JsonElement jsonElement : responses.getJsonObject().getAsJsonArray("docs")) {
			if (jsonElement.getAsJsonObject().get("found").getAsBoolean()) {
				return jsonElement.getAsJsonObject().get("_version").getAsLong();
			}
		}
		return 0L;
	}`

**Comment by VanRoy** [comment]
Hi @umesh936 , you need to inject mappingContext in  ExtendedResultMapper with this value : this.elasticsearchConverter.getMappingContext()

**Comment by umesh936** [comment]
@VanRoy Thanks for quick reply , Does this make sense to you. 
"@Bean
	public JestElasticsearchTemplate elasticsearchTemplate(JestClient client,
			Jackson2ObjectMapperBuilder jackson2ObjectMapperBuilder) {
		MappingElasticsearchConverter converter = new MappingElasticsearchConverter(
				new SimpleElasticsearchMappingContext());
		ExtendedResultMapper mapper = new ExtendedResultMapper(converter.getMappingContext());
		return new JestElasticsearchTemplate(client, converter, mapper);
	}"

**Comment by VanRoy** [comment]
Hi @umesh936 Yes I think it's ok.

**Comment by umesh936** [comment]
@VanRoy I am getting following exception for hitting query for list of object like   find all acounts related to particular customerId.    DumpAccount findByCustomerId(String customerId).. Any lead will be helpful here..  Using version : 	<version>3.0.0.RELEASE</version>

> java.lang.NoSuchMethodError: io.searchbox.core.Search$Builder.addType(Ljava/util/Collection;)Ljava/lang/Object;
> 	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.executeSearch(JestElasticsearchTemplate.java:1313)
> 	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.queryForPage(JestElasticsearchTemplate.java:467)
> 	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.queryForList(JestElasticsearchTemplate.java:423)
> 	at org.springframework.data.elasticsearch.repository.query.ElasticsearchPartQuery.execute(ElasticsearchPartQuery.java:77)
> 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
> 	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
> 	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
> 	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
> 	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
> 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
> 	at com.sun.proxy.$Proxy167.findByCustomerId(Unknown Source)

**Comment by VanRoy** [comment]
Can you ensure that your Jest dependency version is 5.3.3 ?

**Comment by umesh936** [comment]
Apparently I found it is working fine with Jest dependency version is 5.3.2.. My pom is like this now. 
```
<dependency>
			<groupId>com.github.vanroy</groupId>
			<artifactId>spring-boot-starter-data-jest</artifactId>
			<version>3.0.0.RELEASE</version>
			<exclusions>
				<exclusion>
					<groupId>io.searchbox</groupId>
					<artifactId>jest</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.searchbox</groupId>
			<artifactId>jest</artifactId>
			<version>5.3.2</version>
		</dependency>
```

**Comment by VanRoy** [comment]
Thanks for you investigation. I will trying to fix it.
