### ISSUE TITLE
Question: Ignore SSL certificates

### ISSUE THREAD

**Issue by khashayar** [VanRoy/spring-data-jest#65]
I'm using spring-data-jest to connect to AWS ElasticSearch service, which is inside the VPC. In order to access ES, I ssh into an EC2, which is inside the same VPC and use SSH tunneling (Forwarding the localhost port 9200 to ES endpoint port 443).

It works fine except the fact that SSL certificate is not valid on localhost anymore. I can overcome this when using curl with `-k` or accessing through browser. Is there anyway to configure Spring data jest to ignore SSL certificate?

**Comment by VanRoy** [comment]
You can find some information in section SSL of Jest library : https://github.com/searchbox-io/Jest/tree/master/jest
