### ISSUE TITLE
Version 2.3.2 Cannot user scan with order

### ISSUE THREAD

**Issue by icecold21** [VanRoy/spring-data-jest#66]
Hi, i'm trying to use ordering with elasticsearchTemplate scan mode but it doesn't seem i can?
any solution / suggestion? i'm on version 2.3.2

**Comment by VanRoy** [comment]
Hi @icecold21 , Indeed It's seems to be an issue.

Can you send to me a short code snippet to describe your case.
I will fix it quickly.

Thanks.
Julien.

**Comment by VanRoy** [comment]
Ho @icecold21 , I'm sorry by sort is not available at scan method on ES 2.x
Scan is deprecated and replaced by search-scroll.

I'm sorry but there are no quick solution to fix this issue with this version.
