### ISSUE TITLE
No Exception is thrown when JEST result has failure

### ISSUE THREAD

**Issue by rahulsmit** [VanRoy/spring-data-jest#7]
Hi,

I am using ElasticsearchJestAWSAutoConfiguration and I have deliberately entered wrong value for  cloud.aws.credentials.accessKey. 

When I call any Repository method e.g. exists or save, JEST as expected throws an error. - "Cannot execute jest action , response code : 403 , error : 403 Forbidden , message : The security token included in the request is invalid."

But the .save method of my repository doesn't report any exception.

Is this an expected behavior, or there should be an exception. Is there a way to capture the JEST failures?

Thanks,
Rahul

**Comment by VanRoy** [comment]
Hi @rahulsmit , I think it's a bug. I will try to fix it in the next release.

Thanks for your feedback.

**Comment by VanRoy** [comment]
@rahulsmit I fixed this issue on the 2.1.1-SNAPSHOT.
Could you try this version and tell me if it fix you problem.

Thanks.
Julien.
