### ISSUE TITLE
sping boot+jest+aws lambda

### ISSUE THREAD

**Issue by umesh936** [VanRoy/spring-data-jest#71]
I am getting exception "SdkClientException: Unable to load AWS credentials from any provider in the chain" if i run my application through aws Lambda. `Although lambda has IAM role to use Elastic Search and both are in same VPC`. here is complete exception block 

> Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
> 	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
> 	at vc.inreach.aws.request.AWSSigner.getSignedHeaders(AWSSigner.java:91)
> 	at vc.inreach.aws.request.AWSSigningRequestInterceptor.process(AWSSigningRequestInterceptor.java:29)
> 	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
> 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:183)
> 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
> 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
> 	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:132)
> 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:67)
> 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:60)
> 	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.execute(JestElasticsearchTemplate.java:1212)
> 	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.executeWithAcknowledge(JestElasticsearchTemplate.java:1225)
> 	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.indexExists(JestElasticsearchTemplate.java:848)
> 	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndexIfNotCreated(JestElasticsearchTemplate.java:1420)
> 	at com.github.vanroy.springdata.jest.JestElasticsearchTemplate.createIndex(JestElasticsearchTemplate.java:175)
> 	at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.createIndex(AbstractElasticsearchRepository.java:96)
> 	at org.springframework.data.elasticsearch.repository.support.AbstractElasticsearchRepository.<init>(AbstractElasticsearchRepository.java:87)
> 	at org.springframework.data.elasticsearch.repository.support.SimpleElasticsearchRepository.<init>(SimpleElasticsearchRepository.java:36)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170)
> 	... 61 more

**Comment by VanRoy** [comment]
Hi @umesh936 , Do you use Spring Cloud AWS ? Which version ? 
Can you send me simple sample project to reproduce this issue ?
