### ISSUE TITLE
is that possible to do fuzzy search using repository?

### ISSUE THREAD

**Issue by datavisorfrankhe** [VanRoy/spring-data-jest#73]
Hello, May I ask if I want to do following search in AWS elastic search, is that possible to implement through Spring data jest?

```
{
   "_source": [
     "standard_name"
   ],
   "suggest": {
     "school-suggest-fuzzy": {
       "prefix": "standarford",
       "completion": {
         "field": "names.completion",
         "fuzzy": {
           "fuzziness": 1
         }
       }
     }
  }
 }
```

I think I can design entity like this:

```
@Document(indexName="${esindexname}", type="school", shards = 1, replicas = 0, refreshInterval = "-1")
public class School {
	
	@Id
	private String _id;
	@Column(name="standard_name")
	private String standardName;
}
```

And in my repository:

```
public interface SchoolRepository extends ElasticsearchRepository<School, String> {
	List<Company> findByStandardName(String name);
}

```

But nothing is found at all if I search for any school.

If spring data jest is not usable here, do I have to use jest directly here?

Thanks

**Comment by VanRoy** [comment]
Spring Data Jest support all major Spring Data Elasticsearch features.

Do you have tried with the NativeSearchQueryBuilder ( https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.misc ) ?
