### ISSUE TITLE
Upgrade awssigning lib to 0.0.21

### ISSUE THREAD

**Issue by rhanton** [VanRoy/spring-data-jest#77]
I just had the experience of my application failing to connect from an AWS EC2 box to AWS Elasticsearch service with the following error (which I had to introspect by adding logging to the Spring ElasticsearchJestHealthIndicator):
`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`
The problem appeared to be with the version of the aws-signing-request-interceptor library. So I propose moving it up to v0.0.21.

**Comment by VanRoy** [comment]
@rhanton Thanks for your contribution.

**Comment by rhanton** [comment]
No problem!
