### ISSUE TITLE
Upgrade to spring-data-elasticsearch v3.0.10

### ISSUE THREAD

**Issue by rhanton** [VanRoy/spring-data-jest#81]
Looks like they fixed a number of dependencies on apache, jackson, and others and the primary reason is that I want to get access to DATAES-402.

See [Compare v3.0.5.RELEASE to v3.0.10.RELEASE](https://github.com/spring-projects/spring-data-elasticsearch/compare/3.0.5.RELEASE...3.0.10.RELEASE)

**Comment by VanRoy** [comment]
Thanks for your help, it's released in 3.1.5.
