### ISSUE TITLE
Release 3.1.5 not available in maven repository

### ISSUE THREAD

**Issue by DanielFran** [VanRoy/spring-data-jest#85]
Probably an issue while publishing last release, it still not available in maven repository: http://repo.maven.apache.org/maven2/com/github/vanroy/spring-data-jest/

**Comment by VanRoy** [comment]
Hi @DanielFran , it's fixed. Thanks.

**Comment by DanielFran** [comment]
@VanRoy the release is not yet available. Does it take so long usually?

**Comment by VanRoy** [comment]
Normally since 16h30 ( CEST ) it's available on maven central : https://repo1.maven.org/maven2/com/github/vanroy/spring-data-jest/3.1.5.RELEASE/

Can you send me your log of your failed download please.

**Comment by DanielFran** [comment]
OK, it hapears for me now! Sorry about it... Thanks

**Comment by VanRoy** [comment]
Great. Thx.
