### ISSUE TITLE
why not support config es server uris?

### ISSUE THREAD

**Issue by tuser4198** [VanRoy/spring-data-jest#92]
With Suggested config with Spring Boot, I find only uri support.  Like below:

@ConfigurationProperties(prefix = "spring.data.jest")
public class ElasticsearchJestProperties {

	private String uri;
	private String username;
	private String password;

Why not support uris?

**Comment by VanRoy** [comment]
Hi @tuser4198 , It's a good question. I think it will be a great enhancement.
Can you please provide a Pull Request for that ? 
Thanks.

**Comment by tuser4198** [comment]
Sorry, I am too busy recently. I am very glad to provider a PR tomorrow.

**Comment by tuser4198** [comment]
@VanRoy An error ‘path.home not find’ occurred in ElasticsearchJestAutoConfigurationWithProxyTest . I havn't find a quick solution.

**Comment by VanRoy** [comment]
Thanks a lot.
It's available now on release 3.2.2.
