### ISSUE TITLE
Spring Boot Update 2.0.6.RELEASE

### ISSUE THREAD

**Issue by Xyaren** [VanRoy/spring-data-jest#95]
Spring Boot updated to 2.0.6 a week ago.
Can you provide compatibility or is it safe to update already ?

Spring Boot Changelog: https://github.com/spring-projects/spring-boot/releases/tag/v2.0.6.RELEASE

Best Regards

**Comment by VanRoy** [comment]
Hi @Xyaren , Do you had the time to test the compatibility with SB 2.0.6 ?

**Comment by Xyaren** [comment]
As we're using it in a business environment unfortunately not.

Am Di., 20. Nov. 2018, 22:00 hat Julien Roy <notifications@github.com>
geschrieben:

**Comment by VanRoy** [comment]
Hi @Xyaren , the version 3.1.5 is compatible with SpringBoot 2.0.6.
Please feel free to feedback if you detect some issues.
Thanks.
