### ISSUE TITLE
ElasticsearchTemplate is not injected.

### ISSUE THREAD

**Issue by NetoDevel** [VanRoy/spring-data-jest#98]
Thank you for your project!

A doubt:
is it possible for the ElasticsearchTemplate object to be injected?

```
@RestController
@RequestMapping("/user")
public class UserResource {

    @Autowired
    private ElasticsearchTemplate template;
}
```

Error:
`Error creating bean with name 'userResource': Unsatisfied dependency expressed through field 'template'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.data.elasticsearch.core.ElasticsearchTemplate' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}`

**Comment by VanRoy** [comment]
Hi @NetoDevel , indeed ElasticsearchTemplate is not available.
Instead , you can inject ElasticsearchOperations or more specifically JestElasticsearchTemplate

**Comment by NetoDevel** [comment]
@VanRoy,
Thanks for your reply, after reviewing the source code I found the JestElasticsearchTemplate, It seems to work fine!

**Comment by VanRoy** [comment]
@NetoDevel , great. If you do not need use specific feature of Jest ( like custom object mapping ), you can use ElasticsearchOperations. This interface is compatible with both implementation. Your code will be less coupled with SpringDataJest.

Thanks for your feedback.
Julien.
